config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions

  resources :parkingspots do
    member do
      post :offer
    end
  end

  get 'park_spot/index'

  root 'park_spot#index'

end

app/models/occupy.rb
class Occupy < ActiveRecord::Base
  self.table_name = "Occupy"  
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  self.table_name = "Offer"  
end

app/models/parkingspot.rb
class Parkingspot < ActiveRecord::Base
  self.table_name = "ParkingSpot"  
end

app/models/repeatedoffer.rb
class RepeatedOffer < ActiveRecord::Base
  self.table_name = "RepeatedOffer"  
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  self.table_name = "Reserve"  
end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = "User"
  validates_uniqueness_of :UserName
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/park_spot_controller.rb
class ParkSpotController < ApplicationController
  def index
  end
end

app/controllers/parkingspots_controller.rb
class ParkingspotsController < ApplicationController
  def index
    if current_user
      @parkingspots = Parkingspot.where(UserID: current_user.UserID)
    else
      @parkingspots = Parkingspot.all
    end
  end
  def show
    @parkingspot = Parkingspot.find(params[:id])
    @qr = RQRCode::QRCode.new(params[:id], :size => 4, :level => :h )
    @state, @state_by = getState params[:id]
  end
  def new
  end
  def create
    @parkingspot = Parkingspot.new(parkingspot_params)
    @parkingspot.Price = 10
    @parkingspot.xCoor = params[:xCoor]
    @parkingspot.yCoor = params[:yCoor]
    if current_user
      @parkingspot.UserID = current_user.UserID
    end
    @parkingspot.save
    redirect_to @parkingspot
  end
  def destroy
    @parkingspot = Parkingspot.find(params[:id])
    @parkingspot.destroy
    redirect_to parkingspots_path
  end


private
  def parkingspot_params
    params.require(:parkingspot).permit(:UserID, :ParkID, :xCoor, :yCoor)
  end
  def getState(parkID)
    #@state can be "Not Offered" "Offered" "Reserved" "Occupied"
    currentTime = Time.now + 3600*2 #utc + 2 O_o
    occ = Occupy.where("ParkID = ? AND (End is NULL OR End > ?)", parkID, currentTime).take
    if occ
      return "Occupied for " + getTime(occ.End, currentTime), occ.UserID
    end
    res = Reserve.where("ParkID = ? AND (End is NULL OR End > ?)", parkID, currentTime).take
    if res
      return "Reserved for " + getTime(res.End, currentTime), res.UserID
    end
    off = Offer.where("ParkID = ? AND (End is NULL OR End > ?)", parkID, currentTime).take
    if off
      return "Offered for " + getTime(off.End, currentTime), 0
    end
    return "Not Offered", 0
  end
  helper_method :getState
  def getTime myTime, currentTime
    if myTime == nil
      return "ever"
    end
    return humanize(myTime - currentTime)
  end
  def humanize secs
    secs = secs / 60
    [[60, :minutes], [24, :hours], [1000, :days]].inject([]){ |s, (count, name)|
    if secs > 0 
      secs, n = secs.divmod(count)
      s.unshift "#{n.to_i} #{name}"
    end
    s
    }.join(' ')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_UserName(params[:UserName])
    firstHash = Digest::SHA256.hexdigest(params[:password]) 
    if user && Digest::SHA256.hexdigest(firstHash) == user.PW_Hash
      session[:user_id] = user.id
      redirect_to parkingspots_path, notice: "Logged in!"
    else
      flash.now.alert = "User name or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:user][:password] != params[:user][:password_confirmation]
      redirect_to root_url
    end
    @user.Credits = 150
    firstHashed = Digest::SHA256.hexdigest(params[:user][:password])
    @user.PW_Hash = Digest::SHA256.hexdigest(firstHashed) 
    if @user.save
      session[:user_id] = @user.id
      redirect_to parkingspots_path, notice: "Thank you for signing up!"
    else
      redirect_to root_url
    end
  end

private
  def user_params
    params.require(:user).permit(:UserName)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/park_spot_helper.rb
module ParkSpotHelper
end

app/helpers/parkingspots_helper.rb
module ParkingspotsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>ParkSpot</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link href="/jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class= "<%= 'active' if current_page?(root_path) %>"> <%= link_to "Home", root_path %></li>
          <li class = "<%= 'active' if current_page?(parkingspots_path) %>"><%= link_to "My Parking Places", parkingspots_path %></li>
          <!-- <li class = "<%= 'active' if current_page?(root_path) %>"><a href="#">Contact</a></li> -->
        </ul>
        <h3 class="text-muted"><a href="./"><img src="/img/logo.png" width="48" height="48" alt=""></a>ParkSpot</h3>
        <div class="login" align="right">
        <% if  current_user %>
          Logged in as <%= current_user.UserName %>. <%= link_to "Log Out", session_path("current"), method: "delete" %>
        <% else %>
          <%= link_to "Log In", new_session_path %>
        <% end %>
        </div>
      </div> 
      


    <%= yield %>

    <div class="footer">
        <p>&copy; Patchwork 2014</p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>

app/views/park_spot/index.html.erb
      <div class="jumbotron">
        <h1>ParkSpot: Parking made easy</h1>
        <p class="lead">Whether you have own a private parking spot and wish to share it while you are not using it, or you are looking for affordable parking in your area, ParkSpot is the solution.
        </p>
        <p><%= link_to "Sign up today", new_user_path, :class => "btn btn-default" %></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

app/views/parkingspots/index.html.erb
      <div class="jumbotron">
        <h1>Support</h1>
        <p class="lead">Have you tried turning it off and on again?</p>
      </div>
      <% if @parkingspots.first == nil %>
        <p>
        No Parking Spots found
        </p>
      <% else %>
      <table class="table">
      <tr>
        <th>Parking ID</th>
        <% if not current_user %>
          <th>User ID</th>
        <% end %>
        <th>Coordinates</th>
        <th>State</th>
        <th>State by</th>
      </tr>
      <% @parkingspots.find_each { |ps| %>
        <% if  current_user and current_user.UserID != ps.UserID %>
          <% next %>
        <% end %>
        <tr>
          <td><%= link_to ps.ParkID, parkingspot_path(ps.ParkID) %></td>
          <% if not current_user %>
            <td><%= ps.UserID %></td>
          <% end %>
          <td><%= ps.xCoor %>, <%= ps.yCoor %></td>
          <% state, stateby = getState(ps) %>
          <th><%= state %></td>
          <th><%= if stateby != 0
                    stateby
                  end %> 
        </tr>
      <% } %>
      </table>
      <% end %>
      <%= button_to "Add Parking Spot", new_parkingspot_path, :class => "btn btn-default", :method => :get %>
      <p></p> 

app/views/parkingspots/new.html.erb
      <div class="jumbotron">
        <h1>New Parking Spot</h1>
        <p class="lead">Add your Parking Spot to the Database</p>
      </div>


<%= form_for :parkingspot, url: parkingspots_path do |f| %>
  <% if not current_user %>
    <p>
      <%= f.label 'User ID' %><br>
      <%= f.text_field :UserID %>
    </p>
  <% end %>
  <p>
    <%= f.label 'Address' %><br>
    <%= f.text_field :ParkID %>
  </p>
  <%= render_gmap_coordinate_picker %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/parkingspots/show.html.erb
      <div class="jumbotron">
        <h1>View Parking Spot</h1>
        <p class="lead">Display information on "<%= @parkingspot.ParkID %>"</p>
      </div>


<style type="text/css">
table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
}
td {
  border-width: 0; 
  border-style: none;
  border-color: #0000ff; 
  border-collapse: collapse; 
  padding: 0; 
  margin: 0; 
  width: 10px; 
  height: 10px; 
}
td.black { background-color: #000; }
td.white { background-color: #fff; }
</style>
<p>
<div class="map" align="center">
Map Location
<%= render_gmap_coordinate_picker :static => 'true', :zoom_level => 13, :default_coordinates => [@parkingspot.xCoor, @parkingspot.yCoor]  %>
</div>
</p>
<p>
<div class="qr" align="center">
    QR-Code
    <table>
    <% @qr.modules.each_index do |x| %>
      <tr>  
      <% @qr.modules.each_index do |y| %>
       <% if @qr.dark?(x,y) %>
        <td class="black"/>
       <% else %>
        <td class="white"/>
       <% end %>
      <% end %>
      </tr>
    <% end %>
    </table>
</div>
</p>
<div align="center">
<p>
  <strong>Currently this Parking Spot is 
                    <%= @state %> <%= if @state_by != 0
                      ", by " + @state_by.to_s
                    end %></strong>
</p>
</div>
<div class="btn-group">
<% if @state == 'Not Offered' %>
       <%= link_to "Delete", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
       <%= link_to "Offer", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
   <% elsif @state[0..6] == "Offered" %>
       <%= link_to "Remove Offering", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
       <%= link_to "Reserve", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
       <%= link_to "Park", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
   <% elsif @state[0..7] == "Reserved" %>
       <%= link_to "Remove Reservation", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
       <%= link_to "Park", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
   <% elsif @state[0..7] == "Occupied" %>
       <%= link_to "Done Parking", @parkingspot, method: :delete, data: { confirm: 'Do you really want to delete this Parking Spot?' }, :class => "btn btn-default" %>
   <% end %>
</div>

app/views/users/new.html.erb
      <div class="jumbotron">
        <h1>Sign Up</h1>
        <p class="lead">Create a new User Account</p>
      </div>


<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do | message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "User Name" %><br />
    <%= f.text_field :UserName %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>